@URL = {{BASE_URL}}/database

### GET /synchronize
GET {{URL}}/synchronize?accountId=d7f28702-1403-47b9-8710-4901182ddd43

### POST /synchronize
POST {{URL}}/synchronize
Content-Type: application/json

{
  "createdCredentials": [],
  "updatedCredentials": [],
  "deletedCredentialsIds": []
}