@URL = {{BASE_URL}}/database

### GET /synchronize
GET {{URL}}/synchronize?accountId=f60a637c-03c1-432a-8615-40c519f75c8a

### POST /synchronize
POST {{URL}}/synchronize
Content-Type: application/json

{
  "createdCredentials": [],
  "updatedCredentials": [],
  "deletedCredentialsIds": []
}