@URL = {{BASE_URL}}/notifications
@ACCOUNT_ID = b81acdf9-4d4a-463a-af96-1a10024148a8

### Send notification
POST {{URL}}/{{ACCOUNT_ID}}
Content-Type: application/json

{
  "title": "Password Leak",
  "message": "Verificação de violação de senha realizada com sucesso",
  "route": "d7f28702-1403-47b9-8710-4901182ddd43"
}