@URL = {{BASE_URL}}/notifications
@ACCOUNT_ID = b364e0f0-5eac-4fc1-b992-f01b4d72a902

### Send notification
POST {{URL}}/{{ACCOUNT_ID}}
Content-Type: application/json

{
  "title": "Password Leak",
  "message": "Verificação de violação de senha realizada com sucesso",
  "route": "d7f28702-1403-47b9-8710-4901182ddd43"
}