import {
  Mail,
  ChevronDown,
  ChevronUp,
  KeyRound,
  FileType,
  LogOut,
  DiamondPlus,
  NotebookText,
  CircleUserRound,
  List,
  Vault,
  User,
  type LucideIcon,
  EyeIcon,
  EyeOffIcon,
  Gamepad2,
  ShoppingBag,
  Building2,
  Utensils,
  Heart,
  GraduationCap,
  Search,
  Plane,
  Wrench,
  Share2,
  Tv,
  ChevronLeft,
} from 'lucide-react-native'

import type { IconName } from '../types/icon-name'

export const ICONS: Record<IconName, LucideIcon> = {
  'arrow-left': ChevronLeft,
  'arrow-down': ChevronDown,
  'arrow-up': ChevronUp,
  'eye-open': EyeIcon,
  'eye-close': EyeOffIcon,
  'social-media': Share2,
  search: Search,
  email: Mail,
  title: FileType,
  plus: DiamondPlus,
  list: List,
  entertainment: Gamepad2,
  shop: ShoppingBag,
  streaming: Tv,
  bank: Building2,
  food: Utensils,
  health: Heart,
  education: GraduationCap,
  travel: Plane,
  service: Wrench,
  profile: CircleUserRound,
  login: User,
  note: NotebookText,
  vault: Vault,
  password: KeyRound,
  exit: LogOut,
}
